language: python

services:
  - docker

install:
- docker pull tp33/django
- docker pull mysql:5.7.14
- mkdir ~/db
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v `pwd`/db:/var/lib/mysql  mysql:5.7.14
- sleep 15
- docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; grant all on test_cs4501.* to 'www'@'%';"
- cd haproxy
- docker build -t haproxy2 .
- cd ..
script:
- ls
- docker-compose up -d
- docker exec -it food_world bash -c "cd food_world && ./manage.py test"