language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull mysql:5.7.14
- mkdir cs4501
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash
- mysql -uroot -p'$3cureUS' -h db
- create user 'www'@'%' identified by '$3cureUS';
- create database cs4501 character set utf8;
- grant all on cs4501.* to 'www'@'%';
- grant all on test_cs4501.* to 'www'@'%';
- ^D
- docker rm web
- docker run -it --name web -p 8000:8000 --link mysql:db -v ~/cs4501/app:/app tp33/django 
- ping db
- exit
script:
- docker-compose up -d
- docker exec -it food_world bash
- cd food_world
- cd food_world
- ./manage.py test