
models:
    container_name: food_world
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./food_world:/app
    ports:
      - "8001:8000"
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./food_world/wsgi.py"

exp:
   container_name: food_world_exp_api
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./food_world_exp_api:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./food_world_exp_api/wsgi.py"

web:
   container_name: food_world_web
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./food_world_web:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./food_world_web/wsgi.py"

web2:
   container_name: food_world_web_2
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8003:8000"
   volumes:
      - ./food_world_web:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./food_world_web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/app
   command: bash -c "python message_script.py"

batch_spark:
   image: tp33/django
   container_name: batch_spark
   links:
      - kafka:kafka
   volumes:
      - ./batch_spark:/app
   command: bash -c "python message.py"
haxproxy2:
  image: haproxy2
  container_name: haproxy2
  links:
    - web:server1
    - web2:server2
  volumes:
      - .:/app
selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"
selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.7.0 && python front_end.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  
  external_links:
    -  mysql:db

  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./batch-map-reduce:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./batch-map-reduce:/tmp/data