models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/food_world/manage.py makemigrations && python /app/food_world/manage.py migrate && python /app/food_world/manage.py loaddata /app/food_world/db.json && mod_wsgi-express start-server --working-directory /app/food_world --reload-on-changes /app/food_world/food_world/wsgi.py"