# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_items', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'verbose_name': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of food item', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(default='Country Not Specified', max_length=100)),
                ('description', models.TextField()),
                ('nutrition_info', models.TextField()),
                ('carts', models.ManyToManyField(blank=True, null=True, related_name='cart', to='food_core.Cart')),
            ],
            options={
                'verbose_name_plural': 'Snacks',
                'verbose_name': 'Snack',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='enter First Name here', max_length=128)),
                ('last_name', models.CharField(help_text='enter Last Name here', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_items', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='food_core.User')),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
                'verbose_name': 'Wishlist',
            },
        ),
        migrations.AddField(
            model_name='snack',
            name='wishlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to='food_core.Wishlist'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='food_core.User'),
        ),
    ]
