# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_core', '0003_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='authenticator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
