# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_core', '0004_auto_20171026_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticator',
            name='authenticator',
        ),
    ]
