# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_core', '0005_remove_authenticator_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='authenticator',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='authenticator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_core.Authenticator'),
        ),
    ]
